### ISSUE TITLE
Carrousel - Famille/enfant 

### ISSUE THREAD

**Issue by oliviabouligny** [adfinitas-app/SSVP-charite.ssvp.fr#3]
À changer : 
- [x] Visuel de fond
- [x] Témoignage à gauche

![Capture d’écran 2022-11-04 à 14 36 41](https://user-images.githubusercontent.com/106542103/199985672-37e3a8d8-d52b-4270-b6e1-8905b2007f60.png)

**Comment by Leap0p0** [comment]
Done !

**Comment by oliviabouligny** [comment]
@Odyce petit souci sur ce témoignage, au premier chargement de la page tout s'affiche bien, mais si je clique sur un autre et que je reviens sur celui-ci, c'est l'ancien qui apparaît. Apparemment, il faut aller voir dans le js pour remplacer ce texte 
<img width="692" alt="Capture d’écran 2022-11-10 à 14 14 59" src="https://user-images.githubusercontent.com/106542103/201101650-0de44ae6-ff8c-400c-8766-d427d623db2d.png">

**Comment by samirat13** [comment]
@Odyce c'est bon pour nous tu peux la clôturer stp. Merci
