### ISSUE TITLE
Carrousel - Personne à la rue

### ISSUE THREAD

**Issue by oliviabouligny** [adfinitas-app/SSVP-charite.ssvp.fr#4]
À changer 
- [x] visuel de fond
- [x] témoignage à gauche
- [x] Chiffres sur le paragraphe à droite

**Comment by oliviabouligny** [comment]
@Odyce il faudrait que 5 000 soit sur la même ligne
<img width="267" alt="Capture d’écran 2022-11-10 à 13 48 46" src="https://user-images.githubusercontent.com/106542103/201095685-33b174b1-5e89-4ed4-9f60-850f4636c397.png">

**Comment by samirat13** [comment]
@Odyce c'est bon pour nous, tu peux clôturer, merci :)
