### ISSUE TITLE
Grille de dons

### ISSUE THREAD

**Issue by oliviabouligny** [adfinitas-app/SSVP-charite.ssvp.fr#8]
À changer : 

- [ ] Motifs branche à remplacer par les étoiles

**Comment by oliviabouligny** [comment]
@Odyce il faut des espaces ici avant chaque signe €
<img width="308" alt="Capture d’écran 2022-11-10 à 13 56 00" src="https://user-images.githubusercontent.com/106542103/201097286-57408d20-3060-4e61-98f8-f28eac245a41.png">
<img width="316" alt="Capture d’écran 2022-11-10 à 13 55 39" src="https://user-images.githubusercontent.com/106542103/201097290-bfc2e999-f6c5-4e9d-aeaa-99ec09af6a78.png">
<img width="328" alt="Capture d’écran 2022-11-10 à 13 55 15" src="https://user-images.githubusercontent.com/106542103/201097292-2d5507f4-f94f-4ca3-ac84-9fab34c64dfa.png">

**Comment by samirat13** [comment]
@Odyce Merci, peux-tu clôturer cette issue stp?
