### ISSUE TITLE
Encart défisc

### ISSUE THREAD

**Issue by oliviabouligny** [adfinitas-app/SSVP-charite.ssvp.fr#9]
À changer : 

- [ ] 2021 à remplacer par 2022 sur tout le paragraphe

**Comment by Leap0p0** [comment]
Done !

**Comment by oliviabouligny** [comment]
@Odyce il faudrait aussi ajouter des espaces avant chaque signe €, % ou parenthèse
<img width="969" alt="Capture d’écran 2022-11-10 à 13 53 00" src="https://user-images.githubusercontent.com/106542103/201096785-e80eb34a-d431-4d9f-8d58-9b7781c41da5.png">

**Comment by samirat13** [comment]
@Odyce Merci, tu peux fermer cette issue.
